openapi: 3.0.0
info:
  version: 1.0.0
  title: Process Management
servers:
  - url: 'http://localhost:3000'
    description: Local Host Env
tags: [{
    "name": "boards",
    "description": "Boards API"
}, {
    "name": "members",
    "description": "Member in board API"
}, {
    "name": "pulse",
    "description": "pulse API"
}, {
    "name": "labels",
    "description": "pulse status labels API"
}]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/boards/:
    get:
      tags: ['boards']
      security:
        - bearerAuth: []
      summary: Get all boards
      responses:
        '200':
          description: Get list of all boards
          content:
            application/json:
              schema:
                required:
                  - boards
                    - boardId
                    - boardName
                    - boardDescription
                properties:
                  boards:
                    type: array
                    properties:
                      boardId:
                        type: string
                      boardName:
                        type: string
                      boardDescription:
                        type: string
                example:
                  boards:
                  - boardId: bec5839f3d699bef073df03
                    boardName: test board
                    boardDescription: test board description
                  - boardId: bec5839f3d699bef073df03
                    boardName: test board
                    boardDescription: test board description
  /api/boards/{boardId}:
    get:
      tags: ['boards']
      security:
        - bearerAuth: []
      summary: Get single board
      responses:
        '200':
          description: Get single board
          content:
            application/json:
              schema:
                required:
                  - boardId
                  - boardName
                  - boardDescription
                properties:
                  boardId:
                    type: string
                    minimum: 1
                    maximum: 5000
                    example: 1
                  boardName:
                    type: string
                    minimum: 1
                    maximum: 5000
                    example: Board Name
                  boardDescription:
                    type: string
                    minimum: 1
                    maximum: 5000
                    example: Board Description

  /api/boards:
    post:
      tags: ['boards']
      security:
        - bearerAuth: []
      summary: Create New Board
      requestBody:
        description: Create New Board
        required: true
        content:
          application/json:
            schema:
              required:
                - boardName
                - boardDescription
              properties:
                boardName:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: New Test Board Name
                boardDescription:
                  type: string
                  minimum: 1
                  maximum: 5000
                  example: New Test Board Description
      responses:
        '201':
          description: Create New Board
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: new board created successfully
  '/api/boards/{boardId}//':
    put:
      tags: ['boards']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Retrive selected board with BoardID
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: Update a board
      requestBody:
        description: Update a board with boardId passed
        required: true
        content:
          application/json:
            schema:
              required:
                - boardName
                - boardDescription
              properties:
                boardName:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: board title new name
                boardDescription:
                  type: string
                  minimum: 1
                  maximum: 5000
                  example: Updated board description
      responses:
        '200':
          description: Updated a board
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: board updated successfully
  '/api/boards/{boardId}/':
    delete:
      tags: ['boards']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: delete a board by boardId
          schema:
            type: number
            example: 1
      summary: Delete a board
      responses:
        '200':
          description: Deleted a board
          content:
            application/json:
              schema:
                required:
                  - boardId
                  - message
                properties:
                  boardId:
                    type: string
                    example: bec5839f3d699bef073df03
                  message:
                    type: string
                    example: Board deleted sucessfully.
  '/api/{boardId}/members':
    put:
      tags: ['members']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: Update members in a board
      requestBody:
        description: Update a board with boardId passed
        required: true
        content:
          application/json:
            schema:
              required:
                - userDisplayName
                - userEmail
              properties:
                userDisplayName:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: santosh
                userEmail:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: santroshg@gmail.com
      responses:
        '200':
          description: updated members in a board
          content:
            application/json:
              schema:
                required:
                  - userId
                  - userDisplayName
                  - userEmai
                  - message
                properties:
                  userId:
                    type: string
                    example: bec5839f3d699bef073df03
                  userDisplayName:
                    type: string
                    example: santosh
                  userEmail:
                    type: string
                    example: santroshg@gmail.com
                  message:
                    type: string
                    example: member added to board sucessfully.
  '/api/{boardId}/members/{memberId}':
    delete:
      tags: ['members']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: memberId
          in: path
          required: true
          description: memberId
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: delete member in a board
      responses:
        '200':
          description: delete member in a board
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: member deleted sucessfuly from Board.
  '/api/{boardId}/pulse/':
    get:
      tags: ['pulse']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: get all pulse
      responses:
        '200':
          description: get all pulse
          content:
            application/json:
              schema:
                required:
                  - pulseId
                  - pulseCreateTime
                  - pulseCreatedBy
                  - cells
                    - cellId
                    - headerId
                    - cellType
                    - cellLabelTxt
                    - cellColor
                    - cellCreatedOn
                    - cellUpdatedOn
                    - lables
                      - labelId
                      - labelTxt
                      - 
                properties:
                  pulseId:
                    type: string
                    minimum: 1
                    maximum: 5000
                    example: bec5839f3d699bef073df03
                  pulseCreateTime:
                    type: string
                    minimum: 1
                    maximum: 5000
                    example: '2019-02-15T06:44:14Z'
                  pulseCreatedBy:
                    type: string
                    minimum: 1
                    maximum: 5000
                    example: bec5839f3d699bef073df03
                  cells: 
                    type: array
                    items:
                      type: object
                      properties:
                        cellId:
                          type: integer
                        headerId:
                          type: integer
                        cellType:
                          type: string
                        cellLabelTxt: 
                          type: string
                        cellColor: 
                          type: string
                        cellCreatedOn:
                          type: string
                        cellUpdatedOn:
                          type: string
                        labels:
                          type: array
                          items: 
                              type: object
                              properties:
                                labelId:
                                  type: string
                                labelTxt: 
                                  type: string
                                labelColor: 
                                 type: string
                          
                    example:
                      - cellId: bec5839f3d699bsdfsdf03
                        headerId: bec5839f3d6sdfsbef073df03
                        cellType: text
                        cellLabelTxt: Task
                        cellColor: none
                        cellCreatedOn: "2019-02-15T06:44:14Z"
                        cellUpdatedOn: "2019-02-15T06:44:14Z"
                      - cellId: bec5839f3d699bef073df03
                        headerId: bec5839f3d699bef073df03
                        cellType: status
                        cellLabelTxt: completed
                        cellColor: red
                        cellCreatedOn: "2019-02-15T06:44:14Z"
                        cellUpdatedOn: "2019-02-15T06:44:14Z"
                        labels:
                            - labelId: bec5839f3d699bef073df03
                              labelTxt: Comleted
                              labelColor: red
                              
                        
  '/api/{boardId}/pulse':
    post:
      tags: ['pulse']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: create pulse
      requestBody:
        description: create pulse in board with boardId passed
        required: true
        content:
          application/json:
            schema:
              required:
                - headerId
                - cellLabelTxt
                - cellColor
              properties:
                headerId:
                  type: string
                  example: bec5839f3d699bef073df03
                cellLabelTxt:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: Task
                cellColor:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: red
      responses:
        '201':
          description: create pulse in board
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: pulse created sucessfully.
  '/api/{boardId}/pulse/{pulseId}/':
    put:
      tags: ['pulse']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: pulseId
          in: path
          required: true
          description: pulseId
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: update pulse
      requestBody:
        description: updagte pulse in board with boardId & pulseId passed
        required: true
        content:
          application/json:
            schema:
              required:
                - cellId
                - headerId
                - cellLabelTxt
                - cellColor
              properties:
                cellId:
                  type: string
                  example: bec5839f3d699bef073df03
                headerId:
                  type: string
                  example: bec5839f3d699bef073df03
                cellLabelTxt:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: Task
                cellColor:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: red
      responses:
        '200':
          description: update pulse in board
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: pulse updated sucessfully. 
  '/api/{boardId}/pulse/{pulseId}':
    delete:
      tags: ['pulse']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: pulseId
          in: path
          required: true
          description: pulseId
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: delete pulse
      responses:
        '200':
          description: delete pulse
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: pulse deleted sucessfuly from Board.
  '/api/{boardId}/{pulseId}/{cellId}/labels/':
    get:
      tags: ['labels']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: pulseId
          in: path
          required: true
          description: pulseId
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: cellId
          in: path
          required: true
          description: cellId
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: get all pulse status label
      responses:
        '200':
          description: get all pulse status label
          content:
            application/json:
              schema:
                required:
                  - labels
                    - labelId
                    - labelTxt
                    - labelColor
                properties:
                  labels:
                    type: array
                    properties:
                      items:
                        type: object
                example:
                  labels:
                  - labelId: bec5839f3d699bef073df03
                    labelTxt: Comleted
                    labelColor: red
                  - labelId: bec5839f3d699bef073df03
                    labelTxt: Comleted
                    labelColor: red
  '/api/{boardId}/{pulseId}/{cellId}/labels':
    post:
      tags: ['labels']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: pulseId
          in: path
          required: true
          description: pulseId
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: cellId
          in: path
          required: true
          description: cellId
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: create pulse status label
      requestBody:
        description: create pulse status label
        required: true
        content:
          application/json:
            schema:
              required:
                - cellLabelTxt
                - cellColor
              properties:
                cellLabelTxt:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: Task
                cellColor:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: red
      responses:
        '200':
          description: create pulse status label
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: pulse status label created sucessfully. 
  '/api/{boardId}/{pulseId}/{cellId}/labels/{labelId}':
    put:
      tags: ['labels']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: pulseId
          in: path
          required: true
          description: pulseId
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: cellId
          in: path
          required: true
          description: cellId
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: labelId
          in: path
          required: true
          description: label Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: update pulse status label
      requestBody:
        description: updagte pulse status label
        required: true
        content:
          application/json:
            schema:
              required:
                - cellLabelTxt
                - cellColor
              properties:
                cellLabelTxt:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: Task
                cellColor:
                  type: string
                  minimum: 1
                  maximum: 100
                  example: red
      responses:
        '200':
          description: update pulse status label
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: pulse status label updated sucessfully. 
  '/api/{boardId}/{pulseId}/{cellId}/labels/{labelId}/':
    delete:
      tags: ['labels']
      security:
        - bearerAuth: []
      parameters:
        - name: boardId
          in: path
          required: true
          description: Board Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: pulseId
          in: path
          required: true
          description: pulseId
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: cellId
          in: path
          required: true
          description: cellId
          schema:
            type: string
            example: bec5839f3d699bef073df03
        - name: labelId
          in: path
          required: true
          description: label Id
          schema:
            type: string
            example: bec5839f3d699bef073df03
      summary: update pulse status label
      responses:
        '200':
          description: delete pulse status label
          content:
            application/json:
              schema:
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: pulse status label deleted sucessfully.   